version: "3.3"

services:
  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z-cpuv1
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
  mc:
    image: minio/mc:RELEASE.2025-04-08T15-39-49Z-cpuv1
    depends_on:
      - minio
    entrypoint: [ "/bin/sh", "-c", "/init/create-bucket.sh" ]
    volumes:
      - ./init:/init
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - BUCKET_A_NAME=${BUCKET_A_NAME}
      - BUCKET_B_NAME=${BUCKET_B_NAME}
      - BUCKET_ACCESS_KEY=${BUCKET_ACCESS_KEY}
      - BUCKET_SECRET_KEY=${BUCKET_SECRET_KEY}
  httpbin:
    image: cyching/go-httpbin:20250124-fe6c2b26
    ports:
      - '80:80'
    command: 
      - "/bin/go-httpbin"
      - "-port" 
      - "80"
  nextjs-player:
    build:
      context: ./test/nextjs-player
    ports:
      - "3000:3000"
    # volumes:
    #   - ./test/nextjs-player:/app
    #   - /app/node_modules
    #   - /app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true
  fluent-bit:
    image: fluent/fluent-bit:4.0.0
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/scripts:/fluent-bit/scripts
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    command: -c /fluent-bit/etc/fluent-bit.conf

  openresty:
    build: ./openresty
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./openresty/conf/nginx.conf:/opt/bitnami/openresty/nginx/conf/nginx.conf
      - ./openresty/certs:/opt/bitnami/openresty/nginx/conf/certs
      - ./openresty/apikeys:${SECDN_APIKEY_DIR}
      - ./openresty/lua:/opt/bitnami/openresty/nginx/lua
      - ./test/lua:/test/lua
    environment:
      - SECDN_APIKEY_DIR=${SECDN_APIKEY_DIR}
      - MINIO_SECRET_KEY=${BUCKET_SECRET_KEY}
    depends_on:
      - minio
      - mc
      - httpbin
      - nextjs-player
      - fluent-bit
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: openresty.{{.Name}}